Программа запущена: 20250321_161408
2025-03-21 16:14:08,318 - GasAppLogger - DEBUG - Инициализация Result
2025-03-21 16:14:08,334 - GasAppLogger - INFO - GasCompositionManager инициализирован
2025-03-21 16:14:08,340 - GasAppLogger - INFO - Инициализация TableManager
2025-03-21 16:14:08,340 - GasAppLogger - DEBUG - Создание виджетов для управления таблицами
2025-03-21 16:14:08,340 - GasAppLogger - INFO - Создание кнопки 'Исходные таблицы'
2025-03-21 16:14:08,343 - GasAppLogger - DEBUG - Кнопка 'Исходные таблицы' размещена в интерфейсе
2025-03-21 16:14:08,343 - GasAppLogger - DEBUG - Список доступных типов таблиц: ['Таблица для регуляторов', 'Таблица котельной', 'Таблицы для труб до регулятора', 'Таблицы для труб после регулятора']
2025-03-21 16:14:09,714 - GasAppLogger - INFO - Вызов метода check_table_func
2025-03-21 16:14:09,714 - GasAppLogger - WARNING - Список таблиц пуст. Создаем новое окно.
2025-03-21 16:14:09,714 - GasAppLogger - INFO - Создание окна выбора таблиц
2025-03-21 16:14:09,714 - GasAppLogger - DEBUG - Окно таблиц создано
2025-03-21 16:14:09,720 - GasAppLogger - DEBUG - Метка 'Выберите таблицу' добавлена в окно
2025-03-21 16:14:09,724 - GasAppLogger - DEBUG - Combobox инициализирован с вариантами: ['Таблица для регуляторов', 'Таблица котельной', 'Таблицы для труб до регулятора', 'Таблицы для труб после регулятора']
2025-03-21 16:14:09,726 - GasAppLogger - DEBUG - Кнопка 'Добавить таблицу' добавлена в окно
2025-03-21 16:14:11,786 - GasAppLogger - INFO - Начало определения новой таблицы
2025-03-21 16:14:11,786 - GasAppLogger - DEBUG - Выбранный тип таблицы: Таблица для регуляторов
2025-03-21 16:14:11,786 - GasAppLogger - DEBUG - Создание метки для нового типа таблицы
2025-03-21 16:14:11,789 - GasAppLogger - DEBUG - Создание поля ввода имени таблицы
2025-03-21 16:14:11,794 - GasAppLogger - INFO - Интерфейс для создания/открытия таблицы инициализирован
2025-03-21 16:14:12,594 - GasAppLogger - INFO - Попытка открытия таблицы '' типа 'Таблица для регуляторов'
2025-03-21 16:14:12,594 - GasAppLogger - WARNING - Таблица '' не найдена. Создаем новую.
2025-03-21 16:14:12,594 - GasAppLogger - INFO - Попытка добавления таблицы '' типа 'Таблица для регуляторов'
2025-03-21 16:14:12,594 - GasAppLogger - DEBUG - Создание менеджера таблицы через TableFactory
2025-03-21 16:14:12,594 - GasAppLogger - INFO - Запрос на создание менеджера таблицы типа: 'Таблица для регуляторов'
2025-03-21 16:14:12,594 - GasAppLogger - DEBUG - Параметры: parent=.!notebook.!frame, data_model=<__main__.Data_model object at 0x000001CF709DF770>
2025-03-21 16:14:12,594 - GasAppLogger - INFO - Создан менеджер таблицы регуляторов
2025-03-21 16:14:12,594 - GasAppLogger - INFO - Начинаем создание таблицы ''
2025-03-21 16:14:12,594 - GasAppLogger - DEBUG - Получены колонки: ['regulator', 'kv', 'lines_count']
2025-03-21 16:14:12,594 - GasAppLogger - DEBUG - SQL-запрос создания таблицы: 
                CREATE TABLE IF NOT EXISTS  (
                    regulator REAL, kv REAL, lines_count REAL
                )
            
2025-03-21 16:14:12,594 - GasAppLogger - DEBUG - SQL-запрос вставки данных: 
                INSERT INTO  (regulator, kv, lines_count) 
                VALUES (?, ?, ?)
            
2025-03-21 16:14:12,604 - GasAppLogger - INFO - Выполняем создание таблицы '' в базе данных
2025-03-21 16:14:12,606 - GasAppLogger - ERROR - Ошибка SQLite при создании таблицы '': near "(": syntax error
2025-03-21 16:14:12,606 - GasAppLogger - ERROR - Запрос: 
                CREATE TABLE IF NOT EXISTS  (
                    regulator REAL, kv REAL, lines_count REAL
                )
            
2025-03-21 16:14:15,912 - GasAppLogger - INFO - Данные таблицы {'': [<__main__.RegulatorTableManager object at 0x000001CF70A5B470>, 'Таблица для регуляторов']} добавлены в Data_model
2025-03-21 16:14:15,912 - GasAppLogger - INFO - Таблица '' добавлена в реестр
2025-03-21 16:14:15,912 - GasAppLogger - DEBUG - Открытие окна таблицы через менеджер
2025-03-21 16:14:15,912 - GasAppLogger - INFO - Открытие окна таблицы ''
2025-03-21 16:14:15,913 - GasAppLogger - DEBUG - Создано новое окно для таблицы ''
2025-03-21 16:14:15,919 - GasAppLogger - DEBUG - Treeview инициализирован с колонками
2025-03-21 16:14:15,919 - GasAppLogger - INFO - Начинаем загрузку данных таблицы ''
2025-03-21 16:14:15,924 - GasAppLogger - ERROR - Неожиданная ошибка при загрузке таблицы ''
Traceback (most recent call last):
  File "C:\Users\shuev\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\sql.py", line 2264, in execute
    cur.execute(sql, *args)
sqlite3.OperationalError: incomplete input

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\shuev\Desktop\Calculate\Main.py", line 479, in load_table
    df = pd.read_sql_query(f"SELECT * FROM {table_name}", conn)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shuev\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\sql.py", line 486, in read_sql_query
    return pandas_sql.read_query(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shuev\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\sql.py", line 2328, in read_query
    cursor = self.execute(sql, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shuev\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\sql.py", line 2276, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql 'SELECT * FROM ': incomplete input
2025-03-21 16:14:18,814 - GasAppLogger - DEBUG - Данные загружены в Treeview
2025-03-21 16:14:18,821 - GasAppLogger - DEBUG - Кнопка сохранения добавлена в окно
2025-03-21 16:14:18,821 - GasAppLogger - DEBUG - Событие двойного клика привязано к редактированию ячеек
2025-03-21 16:14:18,821 - GasAppLogger - INFO - Таблица '' открыта
2025-03-21 16:14:22,706 - GasAppLogger - INFO - Вызов метода check_table_func
2025-03-21 16:14:22,706 - GasAppLogger - INFO - Список таблиц не пуст. Обновляем окно.
2025-03-21 16:14:22,706 - GasAppLogger - INFO - Создание окна выбора таблиц
2025-03-21 16:14:22,706 - GasAppLogger - DEBUG - Окно таблиц создано
2025-03-21 16:14:22,712 - GasAppLogger - DEBUG - Метка 'Выберите таблицу' добавлена в окно
2025-03-21 16:14:22,715 - GasAppLogger - DEBUG - Combobox инициализирован с вариантами: ['Таблица для регуляторов', 'Таблица котельной', 'Таблицы для труб до регулятора', 'Таблицы для труб после регулятора']
2025-03-21 16:14:22,717 - GasAppLogger - DEBUG - Кнопка 'Добавить таблицу' добавлена в окно
2025-03-21 16:14:22,717 - GasAppLogger - DEBUG - Добавление метки для таблицы: 
2025-03-21 16:14:22,723 - GasAppLogger - DEBUG - Метка и кнопка для таблицы '' добавлены в окно
2025-03-21 16:14:24,697 - GasAppLogger - INFO - Попытка открытия таблицы '' типа 'Таблица для регуляторов'
2025-03-21 16:14:24,697 - GasAppLogger - DEBUG - Открытие окна таблицы через менеджер
2025-03-21 16:14:24,697 - GasAppLogger - INFO - Открытие окна таблицы ''
2025-03-21 16:14:24,698 - GasAppLogger - DEBUG - Создано новое окно для таблицы ''
2025-03-21 16:14:24,704 - GasAppLogger - DEBUG - Treeview инициализирован с колонками
2025-03-21 16:14:24,706 - GasAppLogger - INFO - Начинаем загрузку данных таблицы ''
2025-03-21 16:14:24,706 - GasAppLogger - ERROR - Неожиданная ошибка при загрузке таблицы ''
Traceback (most recent call last):
  File "C:\Users\shuev\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\sql.py", line 2264, in execute
    cur.execute(sql, *args)
sqlite3.OperationalError: incomplete input

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\shuev\Desktop\Calculate\Main.py", line 479, in load_table
    df = pd.read_sql_query(f"SELECT * FROM {table_name}", conn)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shuev\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\sql.py", line 486, in read_sql_query
    return pandas_sql.read_query(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shuev\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\sql.py", line 2328, in read_query
    cursor = self.execute(sql, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shuev\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\sql.py", line 2276, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql 'SELECT * FROM ': incomplete input
2025-03-21 16:14:25,905 - GasAppLogger - DEBUG - Данные загружены в Treeview
2025-03-21 16:14:25,913 - GasAppLogger - DEBUG - Кнопка сохранения добавлена в окно
2025-03-21 16:14:25,913 - GasAppLogger - DEBUG - Событие двойного клика привязано к редактированию ячеек
2025-03-21 16:14:25,913 - GasAppLogger - INFO - Таблица '' открыта
